#ifndef DOS_SERVICES_FILES_CONSTANTS_H
#define DOS_SERVICES_FILES_CONSTANTS_H

#define DOS_EOF             0xFFFF

#define DOS_STDIN_HANDLE    0
#define DOS_STDOUT_HANDLE   1
#define DOS_STDERR_HANDLE   2
#define DOS_PRN_HANDLE      3

#endif
